baseURL = "https://sakurachan.info/posts"
languageCode = "en-us"
title = "Sakura-chan blog"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
# googleAnalytics = ""
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
custom_css = ["/css/syntax.css", "/css/custom.css"]
